name: Linting and style checking

on: [push, pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Prepare
        run: |
          sudo apt-get update
          sudo apt-get install luarocks
          sudo apt-get install clang-tidy
          sudo apt-get install python3-pip
          sudo luarocks install luacheck
          sudo pip3 install compiledb
          make db

      - name: Lint
        run: make lint

  format:
    name: Format
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Prepare
        run: |
          sudo apt-get update
          sudo apt-get install clang-format

      - name: Format
        run: make format
